version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels: ['dependencies', 'area:ci']
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels: ['dependencies']
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(deps-dev)'
      include: 'scope'
    groups:
      minor-and-patch:
        update-types: ['minor', 'patch']
    open-pull-requests-limit: 10
