version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    labels: ['dependencies', 'area:ci']
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    labels: ['dependencies']
    groups:
      minor-and-patch:
        update-types: ['minor', 'patch']
    open-pull-requests-limit: 10
