name: Auto Sub-issue Linker
on:
  issues:
    types: [opened, edited]
permissions:
  issues: write
  contents: read
jobs:
  link-sub-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Extract parent from body
        id: parse
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || '';
            const m = body.match(/Parent:\s*#(\d+)/i);
            core.setOutput('parent', m ? m[1] : '');
      - name: Install gh-sub-issue extension
        if: steps.parse.outputs.parent != ''
        run: gh extension install yahsan2/gh-sub-issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Link as sub-issue
        if: steps.parse.outputs.parent != ''
        run: |
          gh sub-issue add ${{ steps.parse.outputs.parent }} $ISSUE -R $REPO
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.number }}
          REPO: ${{ github.repository }}
