name: Auto Link Issue From Branch
on:
  pull_request:
    types: [opened, edited, synchronize]
permissions:
  pull-requests: write
jobs:
  ensure-linked-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Derive issue number from branch
        id: derive
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.payload.pull_request.head.ref;
            // patterns: docs/0007-title, feat/123-something, 42-anything
            const m = branch.match(/(?:^|\/)(\d{1,6})-?/);
            core.setOutput('issue', m ? m[1] : '');
      - name: Append Closes to PR body when missing
        if: steps.derive.outputs.issue != ''
        uses: actions/github-script@v7
        env:
          ISSUE: ${{ steps.derive.outputs.issue }}
        with:
          script: |
            const issue = process.env.ISSUE;
            const pr = context.payload.pull_request;
            const body = pr.body || '';
            const hasCloses = new RegExp(`(closes|fixes|resolves)\\s+#${issue}`, 'i').test(body);
            if (!hasCloses) {
              const updated = `Closes #${issue}\n\n${body}`.trim();
              await github.rest.pulls.update({ ...context.repo, pull_number: pr.number, body: updated });
            }
