name: PR Housekeeping
on:
  schedule:
    - cron: '7 3 * * *'
  workflow_dispatch: {}
permissions:
  contents: read
  pull-requests: read
  issues: write
jobs:
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: Summarize open PRs and post to parent issue #63
        uses: actions/github-script@v7
        with:
          script: |
            const parent = 63; // Phase 1 親Issue
            const { data: prs } = await github.rest.pulls.list({ ...context.repo, state: 'open', per_page: 100 });
            const rows = [];
            for (const pr of prs) {
              const headSha = pr.head.sha;
              const { data: status } = await github.rest.repos.getCombinedStatusForRef({ ...context.repo, ref: headSha });
              const checks = status.state; // success|failure|pending
              rows.push({ number: pr.number, title: pr.title, draft: pr.draft, labels: pr.labels.map(l=>l.name).join(','), checks });
            }
            const fmt = rows.map(r => `- #${r.number} ${r.title}  [draft:${r.draft?'yes':'no'}]  [labels:${r.labels||'-'}]  [checks:${r.checks}]`).join('\n');
            const body = `PRサマリ（自動生成）\n\n${fmt || 'open PRなし'}\n\n条件: checks=success かつ draft=no かつ レビューOK → マージ可。`;
            await github.rest.issues.createComment({ ...context.repo, issue_number: parent, body });
