name: PR Helper

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  comment-checklist:
    runs-on: ubuntu-latest
    steps:
      - name: Post self-review checklist
        uses: actions/github-script@v8
        with:
          script: |
            const body = `以下の自己レビューを確認してください:\n\n- [ ] 1PR=1論点・小粒か\n- [ ] 日本語で概要・理由・受入条件を記載\n- [ ] Closes #<親Issue> を本文先頭に記載\n- [ ] lint/format/test/md/links/mermaid 済み\n- [ ] スクショや計測を添付（必要なら）\n- [ ] 機微情報なし\n`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body
            });
