name: PR title must be Japanese
on:
  pull_request:
    types: [opened, edited, synchronize, labeled, reopened, ready_for_review]
permissions:
  pull-requests: read
jobs:
  check-title:
    if: ${{ !contains(join(github.event.pull_request.labels.*.name, ','), 'rules:allow-non-jp-title') }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title contains Japanese characters
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.pull_request?.title || '';
            const re = /[\u3040-\u30ff\u3400-\u9fff]/; // hiragana|katakana|cjk
            if (!re.test(title)) {
              core.setFailed(`PRタイトルを日本語にしてください（例: "docs: 〜を追加"）。現在: "${title}"`);
            }
